# Generated by Django 4.0.4 on 2022-06-09 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_alter_postcomment_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=900, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publised', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment', to='post.postcomment')),
            ],
        ),
    ]
